"""edit program name

Revision ID: 0351ad49badf
Revises: 90edbc3ca050
Create Date: 2025-10-28 11:00:53.964436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0351ad49badf'
down_revision: Union[str, Sequence[str], None] = '90edbc3ca050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracurricularprogram_name'), table_name='extracurricularprogram')
    op.drop_table('extracurricularprogram')
    op.drop_index(op.f('ix_certification_name'), table_name='certification')
    op.drop_table('certification')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('studentprofile')
    op.drop_index(op.f('ix_curriculumtrack_name'), table_name='curriculumtrack')
    op.drop_table('curriculumtrack')
    op.add_column('course', sa.Column('curriculumprogram_relation', sa.String(length=10), nullable=False))
    op.add_column('program_requirement', sa.Column('curriculum_name', sa.String(length=200), nullable=False, comment='교육과정명(사람이 보는 명칭; display용)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_requirement', 'curriculum_name')
    op.drop_column('course', 'curriculumprogram_relation')
    op.create_table('curriculumtrack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('curriculumtrack_pkey'))
    )
    op.create_index(op.f('ix_curriculumtrack_name'), 'curriculumtrack', ['name'], unique=False)
    op.create_table('studentprofile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('studentprofile_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('certification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('certification_pkey'))
    )
    op.create_index(op.f('ix_certification_name'), 'certification', ['name'], unique=False)
    op.create_table('extracurricularprogram',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('extracurricularprogram_pkey'))
    )
    op.create_index(op.f('ix_extracurricularprogram_name'), 'extracurricularprogram', ['name'], unique=False)
    # ### end Alembic commands ###
