"""add status to student (soft delete)

Revision ID: 05f4b692eb15
Revises: 0351ad49badf
Create Date: 2025-11-10 10:56:27.246752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05f4b692eb15'
down_revision: Union[str, Sequence[str], None] = '0351ad49badf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certification_name'), table_name='certification')
    op.drop_table('certification')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_curriculumtrack_name'), table_name='curriculumtrack')
    op.drop_table('curriculumtrack')
    op.drop_index(op.f('ix_extracurricularprogram_name'), table_name='extracurricularprogram')
    op.drop_table('extracurricularprogram')
    op.drop_table('studentprofile')
    op.add_column('student', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'status')
    op.create_table('studentprofile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('studentprofile_pkey'))
    )
    op.create_table('extracurricularprogram',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('extracurricularprogram_pkey'))
    )
    op.create_index(op.f('ix_extracurricularprogram_name'), 'extracurricularprogram', ['name'], unique=False)
    op.create_table('curriculumtrack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('curriculumtrack_pkey'))
    )
    op.create_index(op.f('ix_curriculumtrack_name'), 'curriculumtrack', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('certification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('certification_pkey'))
    )
    op.create_index(op.f('ix_certification_name'), 'certification', ['name'], unique=False)
    # ### end Alembic commands ###
