"""float->int

Revision ID: 62b949686229
Revises: 68be0ab1d8aa
Create Date: 2025-10-27 21:52:19.132810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b949686229'
down_revision: Union[str, Sequence[str], None] = '68be0ab1d8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'curriculumprogram_relation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('curriculumprogram_relation', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
