"""make email_other required, email_snu optional

Revision ID: 68be0ab1d8aa
Revises: f4a9f5cbb771
Create Date: 2025-10-27 02:15:59.899432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68be0ab1d8aa'
down_revision: Union[str, Sequence[str], None] = 'f4a9f5cbb771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'email_snu',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('student', 'email_other',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('student_leave_history', 'leave_year',
               existing_type=sa.INTEGER(),
               comment='휴학 연도',
               existing_comment='휴학 시작 연도',
               existing_nullable=False)
    op.alter_column('student_leave_history', 'leave_semester',
               existing_type=sa.VARCHAR(length=10),
               comment='휴학 학기 (1학기/2학기)',
               existing_comment='휴학 시작 학기 (1학기/2학기)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_leave_history', 'leave_semester',
               existing_type=sa.VARCHAR(length=10),
               comment='휴학 시작 학기 (1학기/2학기)',
               existing_comment='휴학 학기 (1학기/2학기)',
               existing_nullable=False)
    op.alter_column('student_leave_history', 'leave_year',
               existing_type=sa.INTEGER(),
               comment='휴학 시작 연도',
               existing_comment='휴학 연도',
               existing_nullable=False)
    op.alter_column('student', 'email_other',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('student', 'email_snu',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
