"""20251027_01

Revision ID: 90edbc3ca050
Revises: 62b949686229
Create Date: 2025-10-27 22:41:44.405989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90edbc3ca050'
down_revision: Union[str, Sequence[str], None] = '62b949686229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_requirement', 'curriculum_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_requirement', sa.Column('curriculum_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='교육과정명(사람이 보는 명칭; display용)'))
    # ### end Alembic commands ###
