"""init models2

Revision ID: f4a9f5cbb771
Revises: 
Create Date: 2025-10-26 22:46:54.303204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4a9f5cbb771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminaccount',
    sa.Column('admin_id', sa.String(length=20), nullable=False),
    sa.Column('admin_hash', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('business_initiative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('support_agency', sa.String(length=150), nullable=True),
    sa.Column('specialized_institute', sa.String(length=150), nullable=True),
    sa.Column('research_task_name', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('beneficiary_target', sa.Float(), nullable=True),
    sa.Column('output_target', sa.Float(), nullable=True),
    sa.Column('career_linked_target', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date <= end_date', name='ck_business_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'start_date', name='uq_business_project_start')
    )
    op.create_index('ix_business_name', 'business_initiative', ['project_name'], unique=False)
    op.create_table('course',
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('curriculumprogram_relation', sa.String(length=10), nullable=False),
    sa.Column('course_name_ko', sa.String(length=200), nullable=False),
    sa.Column('course_name_en', sa.String(length=200), nullable=True),
    sa.Column('degree_level', sa.String(length=10), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('offering_semester', sa.String(length=20), nullable=False),
    sa.Column('offering_cycle', sa.String(length=10), nullable=False),
    sa.Column('grading_scheme', sa.String(length=10), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=True),
    sa.Column('instructor_name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_index('ix_course_name_en', 'course', ['course_name_en'], unique=False)
    op.create_index('ix_course_name_ko', 'course', ['course_name_ko'], unique=False)
    op.create_table('internship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internship_type', sa.String(length=1), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=False),
    sa.Column('sub_program_name', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('host_org_type', sa.String(length=10), nullable=False),
    sa.Column('host_university_name', sa.String(length=150), nullable=True),
    sa.Column('host_department_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("internship_type IN ('A','B','C','D','E')", name='ck_internship_type'),
    sa.CheckConstraint('start_date <= end_date', name='ck_internship_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_name', 'start_date', name='uq_internship_name_start')
    )
    op.create_index('ix_internship_type', 'internship', ['internship_type'], unique=False)
    op.create_table('optiongroup',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), server_default=sa.text("'string'"), nullable=False),
    sa.CheckConstraint("value_type IN ('string','int','bool','date','json')", name='ck_optiongroup_value_type'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_optiongroup_title', 'optiongroup', ['title'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open_year', sa.Integer(), nullable=False),
    sa.Column('open_month', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.String(length=40), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=False),
    sa.Column('sub_program_name', sa.String(length=100), nullable=True),
    sa.Column('organizer', sa.String(length=50), nullable=True),
    sa.Column('event_material', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("program_type IN ('SNU AI.MED talks 시리즈','기업 견학','병원 견학','교육 및 세미나','성과교류회','박람회','학회','경진대회','기타')", name='ck_program_type_values'),
    sa.CheckConstraint('open_month BETWEEN 1 AND 12', name='ck_open_month_range'),
    sa.CheckConstraint('open_year BETWEEN 2000 AND 2100', name='ck_open_year_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_name', 'open_year', 'open_month', name='uq_program_name_ym')
    )
    op.create_index('ix_program_name', 'program', ['program_name'], unique=False)
    op.create_index('ix_program_type', 'program', ['program_type'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('researcher_id', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('foreigner_reg_no', sa.String(length=100), nullable=True),
    sa.Column('email_snu', sa.String(length=200), nullable=True),
    sa.Column('email_other', sa.String(length=200), nullable=False),
    sa.Column('mobile_phone_num', sa.String(length=30), nullable=False),
    sa.Column('phone_num', sa.String(length=30), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('collaborative_program', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('admission_term', sa.String(length=20), nullable=False),
    sa.Column('admission_type', sa.String(length=50), nullable=False),
    sa.Column('workplace', sa.String(length=200), nullable=True),
    sa.Column('health_insurance_certificate', sa.String(length=200), nullable=True),
    sa.Column('academic_status', sa.String(length=30), nullable=False),
    sa.Column('leave_of_absence', sa.String(length=10), nullable=False),
    sa.Column('advisor_name', sa.String(length=50), nullable=False),
    sa.Column('supervisor_name', sa.String(length=50), nullable=True),
    sa.Column('previous_degree', sa.String(length=50), nullable=False),
    sa.Column('previous_major', sa.String(length=100), nullable=False),
    sa.Column('previous_degree_year', sa.Integer(), nullable=False),
    sa.Column('previous_institution', sa.String(length=150), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('graduation_month', sa.Integer(), nullable=True),
    sa.Column('degree_number', sa.String(length=50), nullable=True),
    sa.Column('graduation_certificate', sa.String(length=200), nullable=True),
    sa.Column('further_study', sa.String(length=20), nullable=True),
    sa.Column('further_study_country', sa.String(length=20), nullable=True),
    sa.Column('further_study_info', sa.String(length=100), nullable=True),
    sa.Column('further_study_type', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('employment_study_type', sa.Boolean(), nullable=True),
    sa.Column('employment_uploaded', sa.String(length=200), nullable=True),
    sa.Column('employment_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("((admission_type = '재직자 전형' AND workplace IS NOT NULL) OR (admission_type <> '재직자 전형' AND workplace IS NULL AND health_insurance_certificate IS NULL))", name='ck_employed_track_fields_required'),
    sa.CheckConstraint("birthdate >= DATE '1900-01-01' AND birthdate <= NOW()", name='ck_birthdate_range'),
    sa.CheckConstraint('admission_year BETWEEN 1990 AND EXTRACT(YEAR FROM NOW())::int + 1', name='ck_admission_year_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_id', name='uq_student_researcher_id'),
    sa.UniqueConstraint('student_no', name='uq_student_student_no')
    )
    op.create_index('ix_student_name', 'student', ['name'], unique=False)
    op.create_table('curriculum_program',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_initiative_id', sa.Integer(), nullable=True, comment='이 교육과정을 주관하는 사업단 사업 ID'),
    sa.Column('program_type', sa.String(length=30), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('degree_type', sa.String(length=30), nullable=False),
    sa.Column('department_type', sa.String(length=50), nullable=False),
    sa.Column('open_year', sa.Integer(), nullable=False),
    sa.Column('open_semester', sa.String(length=20), nullable=False),
    sa.Column('close_year', sa.Integer(), nullable=True),
    sa.Column('close_semester', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(close_semester IS NULL) OR (close_semester IN ('1학기','2학기'))", name='ck_close_semester_values'),
    sa.CheckConstraint("degree_type IN ('학부','대학원','통합')", name='ck_degree_type_values'),
    sa.CheckConstraint("department_type IN ('의과대학','공과대학','첨단융합학부','통합')", name='ck_department_type_values'),
    sa.CheckConstraint("open_semester IN ('1학기','2학기')", name='ck_open_semester_values'),
    sa.CheckConstraint("program_type IN ('인증제','교과인증과정','교과과정')", name='ck_program_type_values'),
    sa.CheckConstraint('(close_year IS NULL) OR (close_year BETWEEN 2000 AND 2100)', name='ck_close_year_range'),
    sa.CheckConstraint('open_year BETWEEN 2000 AND 2100', name='ck_open_year_range'),
    sa.ForeignKeyConstraint(['business_initiative_id'], ['business_initiative.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_type', 'course_name', 'open_year', name='uq_curriculum_unique')
    )
    op.create_index('ix_curriculum_program_name', 'curriculum_program', ['program_type'], unique=False)
    op.create_table('optionitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value_text', sa.String(length=200), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(value_text IS NOT NULL)::int + (value_int  IS NOT NULL)::int + (value_bool IS NOT NULL)::int + (value_date IS NOT NULL)::int + (value_json IS NOT NULL)::int = 1', name='ck_optionitem_exactly_one_value'),
    sa.ForeignKeyConstraint(['group_key'], ['optiongroup.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_optionitem_group_key', 'optionitem', ['group_key'], unique=False)
    op.create_index('uq_optionitem_group_value_bool', 'optionitem', ['group_key', 'value_bool'], unique=True, postgresql_where=sa.text('value_bool IS NOT NULL'))
    op.create_index('uq_optionitem_group_value_date', 'optionitem', ['group_key', 'value_date'], unique=True, postgresql_where=sa.text('value_date IS NOT NULL'))
    op.create_index('uq_optionitem_group_value_int', 'optionitem', ['group_key', 'value_int'], unique=True, postgresql_where=sa.text('value_int IS NOT NULL'))
    op.create_index('uq_optionitem_group_value_json', 'optionitem', ['group_key', 'value_json'], unique=True, postgresql_where=sa.text('value_json IS NOT NULL'))
    op.create_index('uq_optionitem_group_value_text', 'optionitem', ['group_key', 'value_text'], unique=True, postgresql_where=sa.text('value_text IS NOT NULL'))
    op.create_table('participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='student.id 레퍼런스. 내부 재학생/졸업생인 경우에만 세팅'),
    sa.Column('affiliation', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliation', 'name', 'email', name='uq_participant_identity')
    )
    op.create_index('ix_participant_affiliation', 'participant', ['affiliation'], unique=False)
    op.create_index('ix_participant_name', 'participant', ['name'], unique=False)
    op.create_table('student_course_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_enroll_student', 'student_course_enrollment', ['student_id'], unique=False)
    op.create_index('ix_enroll_course', 'student_course_enrollment', ['course_code'], unique=False)
    op.create_table('student_leave_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='휴학한 학생 ID'),
    sa.Column('leave_year', sa.Integer(), nullable=False, comment='휴학 시작 연도'),
    sa.Column('leave_semester', sa.String(length=10), nullable=False, comment='휴학 시작 학기 (1학기/2학기)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("leave_semester IN ('1학기','2학기')", name='ck_leave_semester_values'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_course_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False, comment='해당 교과목이 포함되는 교육과정'),
    sa.Column('course_code', sa.String(length=50), nullable=False, comment='인정되는 교과목 코드'),
    sa.Column('required_flag', sa.String(length=10), nullable=False, comment="'필수' / '선택'"),
    sa.Column('initial_year', sa.Integer(), nullable=False),
    sa.Column('initial_semester', sa.String(length=10), nullable=False),
    sa.Column('final_year', sa.Integer(), nullable=True),
    sa.Column('final_semester', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("required_flag IN ('필수','선택')", name='ck_curriculum_course_required_flag'),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'course_code', name='uq_curriculum_course')
    )
    op.create_index('ix_curriculum_course_course', 'curriculum_course_map', ['course_code'], unique=False)
    op.create_index('ix_curriculum_course_curriculum', 'curriculum_course_map', ['curriculum_id'], unique=False)
    op.create_table('curriculum_internship_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('recognized_credit_ratio', sa.Float(), nullable=False, comment='이 교육과정에서 인턴십 수행 1건(또는 단위기간)당 인정되는 환산값(점수)'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='세부 코멘트 / 트랙 설명 등'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'internship_id', name='uq_curriculum_internship')
    )
    op.create_index('ix_curriculum_internship_curriculum', 'curriculum_internship_map', ['curriculum_id'], unique=False)
    op.create_index('ix_curriculum_internship_internship', 'curriculum_internship_map', ['internship_id'], unique=False)
    op.create_table('curriculum_program_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('recognized_credit_ratio', sa.Float(), nullable=False, comment='이 교육과정에서 이 비교과 1회 참여 시 인정되는 환산값(점수)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recognized_credit_ratio >=0.0', name='ck_recognized_credit_ratio_range'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'program_id', name='uq_curriculum_program')
    )
    op.create_index('ix_curriculum_program_map_curriculum', 'curriculum_program_map', ['curriculum_id'], unique=False)
    op.create_index('ix_curriculum_program_map_program', 'curriculum_program_map', ['program_id'], unique=False)
    op.create_table('internship_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='해당 인턴십 실적을 귀속시킬 학생. 외부인은 NULL'),
    sa.Column('participation_type', sa.String(length=20), nullable=False),
    sa.Column('affiliation_snapshot', sa.String(length=150), nullable=False),
    sa.Column('student_no_snapshot', sa.String(length=30), nullable=True),
    sa.Column('degree_program_snapshot', sa.String(length=20), nullable=True),
    sa.Column('enroll_source', sa.String(length=30), nullable=True, comment='데이터 입력 경로 (manual/excel_upload 등)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_program_snapshot IN ('학사','석사','박사','석박통합','기타') OR degree_program_snapshot IS NULL", name='ck_intern_degree_program'),
    sa.CheckConstraint("participation_type IN ('운영진','교수','조교','연구원','학생','외부')", name='ck_intern_participation_type'),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internship_id', 'participant_id', name='uq_internship_participant')
    )
    op.create_index('ix_intern_enroll_internship', 'internship_enrollment', ['internship_id'], unique=False)
    op.create_index('ix_intern_enroll_participant', 'internship_enrollment', ['participant_id'], unique=False)
    op.create_index('ix_intern_enroll_student', 'internship_enrollment', ['student_id'], unique=False)
    op.create_table('program_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='당시 이 참여를 인정받은 학생 ID. 외부인이면 NULL'),
    sa.Column('participation_type', sa.String(length=20), nullable=False),
    sa.Column('affiliation_snapshot', sa.String(length=150), nullable=False),
    sa.Column('degree_program_snapshot', sa.String(length=20), nullable=True),
    sa.Column('student_no_snapshot', sa.String(length=30), nullable=True),
    sa.Column('recognized_credit', sa.Float(), nullable=True),
    sa.Column('enroll_source', sa.String(length=30), nullable=True, comment='데이터 입력 경로 (manual/excel_upload 등)'),
    sa.Column('exception_case', sa.Boolean(), nullable=False, comment='특이 케이스 여부(예외 인정 등)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_program_snapshot IN ('학사','석사','박사','석박통합','기타') OR degree_program_snapshot IS NULL", name='ck_prog_degree_program'),
    sa.CheckConstraint("participation_type IN ('운영진','교수','조교','연구원','학생','외부')", name='ck_prog_participation_type'),
    sa.CheckConstraint('recognized_credit >= 0 OR recognized_credit IS NULL', name='ck_recognized_credit_nonnegative'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'participant_id', name='uq_program_participant')
    )
    op.create_index('ix_enroll_participant', 'program_enrollment', ['participant_id'], unique=False)
    op.create_index('ix_enroll_program', 'program_enrollment', ['program_id'], unique=False)
    op.create_index('ix_prog_enroll_student', 'program_enrollment', ['student_id'], unique=False)
    op.create_table('program_requirement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False, comment='이 이수조건이 속한 교육과정 ID'),
    sa.Column('requirement_code', sa.String(length=30), nullable=False, comment='YYYY + seq(4자리) + college_code(M/E) + degree_code(B/M/D/C...). 생성 후 수정 금지'),
    sa.Column('college_scope', sa.String(length=20), nullable=False, comment="적용 기준(대학): '의과대학' / '그 외'"),
    sa.Column('degree_scope', sa.String(length=20), nullable=False, comment="적용 기준(학위): '학부','석사','박사','대학원생','통합' 등"),
    sa.Column('curriculum_name', sa.String(length=200), nullable=False, comment='교육과정명(사람이 보는 명칭; display용)'),
    sa.Column('required_credit', sa.Float(), nullable=False, comment='해당 교육과정 이수에 필요한 교과 학점 요구량'),
    sa.Column('total_converted_required', sa.Float(), nullable=False, comment='비교과(프로그램) 인정 환산 점수 합계 최소 요구치'),
    sa.Column('total_internship_required', sa.Float(), nullable=False, comment='인턴십(현장실습) 인정 환산 점수 합계 최소 요구치'),
    sa.Column('min_ai_med_talks', sa.Integer(), nullable=False),
    sa.Column('min_company_visit', sa.Integer(), nullable=False),
    sa.Column('min_hospital_visit', sa.Integer(), nullable=False),
    sa.Column('min_seminar', sa.Integer(), nullable=False),
    sa.Column('min_exchange_forum', sa.Integer(), nullable=False),
    sa.Column('min_expo', sa.Integer(), nullable=False),
    sa.Column('min_academic_conf', sa.Integer(), nullable=False),
    sa.Column('min_competition', sa.Integer(), nullable=False),
    sa.Column('min_etc', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("college_scope IN ('의과대학','그 외')", name='ck_requirement_college_scope'),
    sa.CheckConstraint("degree_scope IN ('학부','석사','박사','대학원생','통합')", name='ck_requirement_degree_scope'),
    sa.CheckConstraint('min_ai_med_talks >= 0 AND min_company_visit >= 0 AND min_hospital_visit >= 0 AND min_seminar >= 0 AND min_exchange_forum >= 0 AND min_expo >= 0 AND min_academic_conf >= 0 AND min_competition >= 0 AND min_etc >= 0', name='ck_requirement_min_attendance_nonneg'),
    sa.CheckConstraint('required_credit >= 0.0', name='ck_requirement_required_credit_nonneg'),
    sa.CheckConstraint('total_converted_required >= 0.0', name='ck_requirement_total_converted_required_nonneg'),
    sa.CheckConstraint('total_internship_required >= 0.0', name='ck_requirement_total_internship_required_nonneg'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_code')
    )
    op.create_index('ix_program_requirement_code', 'program_requirement', ['requirement_code'], unique=False)
    op.create_index('ix_program_requirement_curriculum', 'program_requirement', ['curriculum_id'], unique=False)
    op.create_table('student_curriculum_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_program_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True, comment='학생에게 실제 적용된 ProgramRequirement 버전'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ongoing / completed / withdrawn / suspended'),
    sa.Column('joined_year', sa.Integer(), nullable=True),
    sa.Column('joined_term', sa.String(length=10), nullable=True),
    sa.Column('completed_year', sa.Integer(), nullable=True),
    sa.Column('completed_term', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ongoing','completed','withdrawn','suspended')", name='ck_student_curriculum_status_values'),
    sa.ForeignKeyConstraint(['curriculum_program_id'], ['curriculum_program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['program_requirement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'curriculum_program_id', name='uq_student_curriculum_unique')
    )
    op.create_index('ix_student_curriculum_program', 'student_curriculum_enrollment', ['curriculum_program_id'], unique=False)
    op.create_index('ix_student_curriculum_student', 'student_curriculum_enrollment', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_curriculum_student', table_name='student_curriculum_enrollment')
    op.drop_index('ix_student_curriculum_program', table_name='student_curriculum_enrollment')
    op.drop_table('student_curriculum_enrollment')
    op.drop_index('ix_program_requirement_curriculum', table_name='program_requirement')
    op.drop_index('ix_program_requirement_code', table_name='program_requirement')
    op.drop_table('program_requirement')
    op.drop_index('ix_prog_enroll_student', table_name='program_enrollment')
    op.drop_index('ix_enroll_program', table_name='program_enrollment')
    op.drop_index('ix_enroll_participant', table_name='program_enrollment')
    op.drop_table('program_enrollment')
    op.drop_index('ix_intern_enroll_student', table_name='internship_enrollment')
    op.drop_index('ix_intern_enroll_participant', table_name='internship_enrollment')
    op.drop_index('ix_intern_enroll_internship', table_name='internship_enrollment')
    op.drop_table('internship_enrollment')
    op.drop_index('ix_curriculum_program_map_program', table_name='curriculum_program_map')
    op.drop_index('ix_curriculum_program_map_curriculum', table_name='curriculum_program_map')
    op.drop_table('curriculum_program_map')
    op.drop_index('ix_curriculum_internship_internship', table_name='curriculum_internship_map')
    op.drop_index('ix_curriculum_internship_curriculum', table_name='curriculum_internship_map')
    op.drop_table('curriculum_internship_map')
    op.drop_index('ix_curriculum_course_curriculum', table_name='curriculum_course_map')
    op.drop_index('ix_curriculum_course_course', table_name='curriculum_course_map')
    op.drop_table('curriculum_course_map')
    op.drop_table('student_leave_history')
    op.drop_index('ix_enroll_course', table_name='student_course_enrollment')
    op.drop_index('ix_course_enroll_student', table_name='student_course_enrollment')
    op.drop_table('student_course_enrollment')
    op.drop_index('ix_participant_name', table_name='participant')
    op.drop_index('ix_participant_affiliation', table_name='participant')
    op.drop_table('participant')
    op.drop_index('uq_optionitem_group_value_text', table_name='optionitem', postgresql_where=sa.text('value_text IS NOT NULL'))
    op.drop_index('uq_optionitem_group_value_json', table_name='optionitem', postgresql_where=sa.text('value_json IS NOT NULL'))
    op.drop_index('uq_optionitem_group_value_int', table_name='optionitem', postgresql_where=sa.text('value_int IS NOT NULL'))
    op.drop_index('uq_optionitem_group_value_date', table_name='optionitem', postgresql_where=sa.text('value_date IS NOT NULL'))
    op.drop_index('uq_optionitem_group_value_bool', table_name='optionitem', postgresql_where=sa.text('value_bool IS NOT NULL'))
    op.drop_index('ix_optionitem_group_key', table_name='optionitem')
    op.drop_table('optionitem')
    op.drop_index('ix_curriculum_program_name', table_name='curriculum_program')
    op.drop_table('curriculum_program')
    op.drop_index('ix_student_name', table_name='student')
    op.drop_table('student')
    op.drop_index('ix_program_type', table_name='program')
    op.drop_index('ix_program_name', table_name='program')
    op.drop_table('program')
    op.drop_index('ix_optiongroup_title', table_name='optiongroup')
    op.drop_table('optiongroup')
    op.drop_index('ix_internship_type', table_name='internship')
    op.drop_table('internship')
    op.drop_index('ix_course_name_ko', table_name='course')
    op.drop_index('ix_course_name_en', table_name='course')
    op.drop_table('course')
    op.drop_index('ix_business_name', table_name='business_initiative')
    op.drop_table('business_initiative')
    op.drop_table('adminaccount')
    # ### end Alembic commands ###
